import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import styles from './layout.module.scss'
import RootLayoutClient from "@/Provider/RootLayoutClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
      <html lang="en">
        <body className={`${inter.className} ${styles.container}`}>
          <RootLayoutClient>
            <Sidebar/>
            {children}
          </RootLayoutClient>
        </body>
      </html>
  );
}
