import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import RootLayoutClient from "@/components/Provider/RootLayoutClient";
import Layout from "@/components/Layout/Layout";
// import '../firebase'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
      <html lang="en">
        <RootLayoutClient>
          <Layout>
              <Sidebar/>
              {children}
          </Layout>
        </RootLayoutClient>
      </html>
  );
}
